# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/violet-virgo"
    schedule:
      interval: daily
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "15:00"
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
